main: main.cpp
	g++ -Wall -g $^ -o ./dist/main

mergesort: mergeSort.cpp
	g++ -Wall -g $^ -o ./dist/mergesort

quicksort: quicksort.cpp
	g++ -Wall -g $^ -o ./dist/quicksort

radixsort: radixsort.cpp
	g++ -Wall -g $^ -o ./dist/radixsort